# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CatFacts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'SwiftGen'
  pod 'PureLayout'  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SwiftyJSON', '~> 4.2.0'
  # Pods for CatFacts

  target 'CatFactsTests' do
      # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Nimble-Snapshots'
  end
end
